repos:
    -   repo: https://github.com/pre-commit/pre-commit-hooks
        rev: v4.5.0
        hooks:
        - id: trailing-whitespace
        - id: end-of-file-fixer
        - id: check-yaml
        - id: check-added-large-files
        - id: flake8

    -   repo: https://github.com/psf/black
        rev: 23.11.0
        hooks:
        -   id: black
            args: ["--line-length=88"]

    -   repo: https://github.com/asottile/reorder_python_imports
        rev: v3.12.0
        hooks:
          - id: reorder-python-imports
